version: '3.7'

services: 
  site:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    volumes: 
     - .:/app
    ports: 
     - "3000:3000"
  
  redis:
    image: redis