version: '3.7'

services: 
  site:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    networks: 
     - web
     - backend
    labels: 
     - "traefik.enable=true"
     - "traefik.http.routers.homesite-web.rule=Host(`vardy.dev`) || Host(`www.vardy.dev`)"
     - "traefik.http.routers.homesite-web.entrypoints=web"
     - "traefik.http.routers.homesite-web.middlewares=redirect@file"
     - "traefik.http.routers.homesite-secured.rule=Host(`vardy.dev`) || Host(`www.vardy.dev`)"
     - "traefik.http.routers.homesite-secured.entrypoints=web-secured"
     - "traefik.http.routers.homesite-secured.tls.certresolver=mytlschallenge"
     - "traefik.http.services.homesite.loadbalancer.server.port=3000"
  
  redis:
    image: redis
    networks: 
     - backend

networks: 
  web:
    external: true
  backend:
    external: false
